version: '3.3'

volumes:
  data:

services:

  db:
    image: mongo:${MONGO_VERSION}
    container_name: mongodb
    restart: always
    volumes:
        - "./data/mongo:/data/db"
    ports:
        - "27017:27017"
    command: --storageEngine wiredTiger
    networks:
      - app-networks

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-networks

  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    networks:
      - app-networks

  app:
    build: .
    container_name: ${NAME_APP_WEB}
    ports:
      - "8000:80"
      - "4000:443"
    restart: always
    depends_on:
      - db
      - redis
      - mail
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/usr/share/nginx"
      - "./setup.sh:/usr/share/nginx/setup.sh"
      - "./etc/ssl:/etc/ssl"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
